version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-vue-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-vue-network

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-vue-queue
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        command: php artisan queue:work --tries=3 --timeout=30
        depends_on:
            - app
            - redis
        networks:
            - laravel-vue-network

    nginx:
        image: nginx:alpine
        container_name: laravel-vue-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - laravel-vue-network

    db:
        image: mysql:8.0
        container_name: laravel-vue-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel-vue-network

    redis:
        image: redis:alpine
        container_name: laravel-vue-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel-vue-network

networks:
    laravel-vue-network:
        driver: bridge

volumes:
    dbdata:
